name: torsion_profiler_qm
channels:
  - conda-forge
  - defaults
  - psi4
dependencies:
  # Python
  - python
  - pip
  - notebook
  - tqdm
  - pytest

  # std. Python:
  - matplotlib
  - numpy
  - pandas
  - scipy
  - sklearn

  # Chemistry
  - mdtraj
  - nglview
  - rdkit
  - openff-fragmenter

  # special
  - libecpint
  - psi4
    # 6.7.1 is buggy
  - xtb==6.6.1

  - pip:
    - cclib

